plugins:
  group_tracker_default_icon:
    client: true
    default: "crown"
  group_tracker_topic_icon:
    client: true
    default: ""
  group_tracker_topic_icon_class:
    client: true
    default: ""
